---
# Task file for Container

- name: Download OS Template
  get_url:
    url: "http://download.proxmox.com/images/system/{{ OS_Template }}"
    dest: "/var/lib/vz/template/cache/{{ OS_Template }}"

- name: Create CT
  proxmox:
    vmid: "{{ ctid }}"
    node: "{{ node }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host: "{{ api_host }}"
    hostname: "{{ cthostname }}"
    password: "{{ ctpassword }}"
    searchdomain: "{{ searchdomain }}"
    nameserver: "{{ ctnameserver }}"
    cores: "{{ ctcores }}"
    swap: "{{ ctswap }}"
    memory: "{{ ctmemory }}"
    disk: "{{ ctdisk }}"
    storage: "{{ ctstorage }}"
    netif: '{"net0":"name=eth0,ip={{ ctip }},gw={{ ctgw }},bridge={{ ctbridge }}"}'
    ostemplate: 'local:vztmpl/{{ OS_Template }}'
    state: present
  
- name: Start CT
  proxmox:
    vmid: "{{ ctid }}"
    node: "{{ node }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host: "{{ api_host }}"
    state: started
    timeout: 90