---
# tasks file for vm
- name: Create VMs
  proxmox_kvm:
    vmid: "{{ vmid }}"
    node: "{{ node }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host: "{{ api_host }}"
    name: "{{ vmname }}"
    net: '{"net0":"virtio,bridge={{ vmbridge }}"}'
    virtio: '{"virtio0":"local-lvm:{{ vmdisk }}"}'
    cores: "{{ vmcores }}"
    vcpus: "{{ vmvcpus }}"
    memory: "{{ vmmemory }}"